name       : opentyrian
version    : 2.1.20130907
release    : 1
source     :
    - http://www.camanis.net/opentyrian/releases/opentyrian-2.1.20130907-src.tar.gz : f54b6b3cedcefa187c9f605d6164aae29ec46a731a6df30d351af4c008dee45f
    - http://camanis.net/tyrian/tyrian21.zip : 7790d09a2a3addcd33c66ef063d5900eb81cc9c342f4807eb8356364dd1d9277
license    : GPL-2.0
component  : games.arcade
summary    : OpenTyrian is an open-source port of the DOS game Tyrian.
description: |
    OpenTyrian is an open-source port of the DOS game Tyrian.
builddeps  :
    - pkgconfig(sdl)
    - pkgconfig(SDL_net)
setup      : |
    unzip $sources/tyrian21.zip
    sed -i "s|Icon=opentyrian|Icon=/usr/share/pixmaps/opentyrian.png|" linux/opentyrian.desktop
build      : |
    %make
install    : |
    install -D -m 00755 opentyrian $installdir/usr/bin/opentyrian
    rm -rf tyrian21/*.exe
    install -d -m 00644 $installdir/usr/share/opentyrian/data
    install -m 00644 tyrian21/* $installdir/usr/share/opentyrian/data
    install -D -m 00644 linux/opentyrian.desktop $installdir/usr/share/applications/opentyrian.desktop
    install -D -m 00644 linux/man/opentyrian.6 $installdir/usr/share/man/man6/opentyrian.6
    install -D -m 00644 linux/icons/tyrian-128.png $installdir/usr/share/pixmaps/opentyrian.png
