name       : opentyrian
version    : 2.1.20220309
release    : 3
source     :
    - https://github.com/opentyrian/opentyrian/archive/refs/tags/v2.1.20220309.tar.gz : 6df44ca9b36acf9ba67099621b2fb1baa5f7b4ad2ec924ed943b87ff9061dbd2
    - http://camanis.net/tyrian/tyrian21.zip : 7790d09a2a3addcd33c66ef063d5900eb81cc9c342f4807eb8356364dd1d9277
homepage   : https://github.com/opentyrian/opentyrian
license    : GPL-2.0-or-later
component  : games.arcade
summary    : OpenTyrian is an open-source port of the DOS game Tyrian
description: |
    OpenTyrian is an open-source port of the DOS game Tyrian. Tyrian is an arcade-style vertical scrolling shooter. The story is set in 20,031 where you play as Trent Hawkins, a skilled fighter-pilot employed to fight MicroSol and save the galaxy. Tyrian features a story mode, one- and two-player arcade modes, and networked multiplayer.
builddeps  :
    - pkgconfig(SDL2_net)
    - pkgconfig(sdl2)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-game-version.patch
    unzip $sources/tyrian21.zip
    rm -rf tyrian21/*.exe
build      : |
    %make TYRIAN_DIR=/usr/share/opentyrian
install    : |
    install -Dm00755 opentyrian $installdir/usr/bin/opentyrian
    install -dm00644 $installdir/usr/share/opentyrian
    cp -Rv tyrian21/* $installdir/usr/share/opentyrian
    install -Dm00644 linux/man/opentyrian.6 $installdir/usr/share/man/man6/opentyrian.6
    install -Dm00644 linux/opentyrian.desktop $installdir/usr/share/applications/opentyrian.desktop

    for px in 22 24 32 48 128; do
        install -Dm00644 linux/icons/tyrian-${px}.png \
        $installdir/usr/share/icons/hicolor/${px}x${px}/apps/opentyrian.png
    done
